version: "3.9"
services:
  backend:
    # 1. Không dùng 'build', hãy dùng image đã đẩy lên Docker Hub ở Job 1
    image: ${DOCKERHUB_USERNAME}/api-devops:latest
    container_name: backend-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # 2. Thay chuỗi kết nối bằng biến môi trường
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - DISABLE_HTTPS_REDIRECTION=true
    ports:
      - "5000:8080"