version: "3.9"
services:
  backend:
    build:
      context: ./API-Learn-Devops/API-Learn-Devops
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production # Đổi sang Production
      - ASPNETCORE_URLS=http://+:8080
      # Thay đổi Connection String dưới đây
      - ConnectionStrings__DefaultConnection=Host=my-first-db.cnigoik4kd0b.ap-southeast-2.rds.amazonaws.com;Port=5432;Database=TodoApp;Username=postgres;Password=kyMwyj-tumkax-4zubjy
      - DISABLE_HTTPS_REDIRECTION=true
    ports:
      - "5000:8080"

# Xóa bỏ phần dịch vụ postgres và volumes pgdata vì không dùng đến nữa